### ISSUE TITLE
#hacktoberfest: Create simple dropdown menu in React, based on material ui

### ISSUE THREAD

**Issue by a-tonchev** [a-tonchev/react-boilerplate#13]
For our amazing boilerplate it would be awesome to have a dropdown menu.

The menu should be based on material ui's popper (https://mui.com/components/popper/), it should display all the child components and have 2 variants:

Variant 1, simple menu:

![image](https://user-images.githubusercontent.com/54528540/135717067-eb67e5ec-c3ef-496b-8be2-68bb55abc844.png)

Variant 2, more complex menu:

![image](https://user-images.githubusercontent.com/54528540/135717109-1a6c3123-44a3-45ce-b55e-9f0ec6d26c19.png)

It should receive categories as prop in similar construction:

```
[
  {
    _id: 1,
    name: Products,
    parentId: '',
  },
  {
    _id: 2,
    name: Category1,
    parentId: 1,
  },
  {
    _id: 3,
    name: Category2,
    parentId: 1,
  },
  {
    _id: 4,
    name: Category3,
    parentId: 1,
  },
  {
    _id: 5,
    name: SubCategory5,
    parentId: 2,
  }
  // etc..
]
```

also an attribute `variant`, receiving 'default' or 'complex' to distinguish which variant should be displayed

The menu should appear on hover.

More information about how to contribute read under:

https://github.com/a-tonchev/react-boilerplate/blob/master/contributing.md

**Comment by TaneliR** [comment]
I could try to make this 👍

**Comment by a-tonchev** [comment]
@TaneliR You have the GO :)

**Comment by TaneliR** [comment]
For some reason the project won't start, maybe some dependency issue, or did I forget a step? 🤔 

After I ran `yarn install` and `yarn start` it gets the server up but instantly crashed.

```
events.js:288
      throw er; // Unhandled 'error' event
      ^
C:\ ... \react-boilerplate\node_modules\@nabla\vite-plugin-eslint\worker.js:35
      if (e.messageTemplate === "file-not-found" && e.messageData?.pattern) {
                                                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:162:24)
    at MessagePort.emit (events.js:311:20)
    at MessagePort.onmessage (internal/worker/io.js:78:8)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (internal/worker.js:204:10)
    at Worker.[kOnMessage] (internal/worker.js:214:37)
    at MessagePort.<anonymous> (internal/worker.js:141:57)
    at MessagePort.emit (events.js:311:20)
    at MessagePort.EventEmitter.emit (domain.js:482:12)
    at MessagePort.onmessage (internal/worker/io.js:78:8)
error Command failed with exit code 1.
```

**Comment by a-tonchev** [comment]
@TaneliR hmm, which operating system you are trying?

**Comment by TaneliR** [comment]
Got it working now, updated everything and rebooted. Could've been docker from another project hoggin all the ports or something.

**Comment by a-tonchev** [comment]
@TaneliR cool, yes, it happens sometimes ;)

**Comment by TaneliR** [comment]
One question about this. Is there a reason for the props being in one dimensional array? Messed around a bit, but realized I'd need to parse the array recursively via parentId & the  item _id (since depth of relation is unknown), and it seemed to be a bit overengineered solution.

**Comment by a-tonchev** [comment]
@TaneliR yes, actually the reason is that this is usually the way the categories are stored in the DB.

But when I think about, the server should be able to prepare a multi dimensional array, so it would be also okay to make a multi dimensional array as props, e.g. something like

```
[
 {
   _id: "xyz", 
   name: 'Parent Category', 
  children: [{
      name: "Child 1",
   },
   {
     name: "Child 2",
     children: [etc...] 
    } 
   ] 
  } 
]
```

Or you suggest something else?

**Comment by a-tonchev** [comment]
Hi @TaneliR how is the progress here, do you have any open questions? :)

**Comment by TaneliR** [comment]
Ok I think I have to give up on this. Had too much trouble with materialui, didn't know the components well  enough to work on this comfortably.

**Comment by julieg18** [comment]
To make sure I'm understanding how you would like the `categories` props to be written:

Props for your simple menu image would look like this?
```
const categories = [
  {
    name: 'Dropdown menu',
    link: '/some-link',
  },
  {
    name: 'Dropdown menu',
    link: '/some-link',
  },
  {
    name: 'Dropdown menu',
    link: '/some-link',
  },
  {
    name: 'Dropdown menu',
    link: '/some-link',
  },
];
```

Props for your complex menu image would look like this?
```
const categories = [
  {
    name: 'Aliquam Metus Vitae',
    children: [
      {
        name: 'Quisque orci augue',
        link: '/some-link',
      },
      {
        name: 'Laoreet amet ante',
        link: '/some-link',
      },
      {
        name: 'Aenean quam vitae',
        link: '/some-link',
      },
      {
        name: 'Aliquam ac semper',
        link: '/some-link',
      },
      {
        name: 'Nulla liqula puvinar',
        link: '/some-link',
      },
    ],
  },
  {
    name: 'Lobortis Sem Mauris',
    children: [
      {
        name: 'Aenean quam vitae',
        link: '/some-link',
      },
      {
        name: 'Nulla ligula pulvinar',
        link: '/some-link',
      },
      {
        name: 'Quisque orci augue',
        link: '/some-link',
      },
      {
        name: 'Aliquam ac lobortis',
        link: '/some-link',
      },
      {
        name: 'Laoreet sem sodales',
        link: '/some-link',
      },
    ],
  },
  ...etc
];
```

**Comment by a-tonchev** [comment]
@julieg18 yes, this would be okay.
